---
title: "1 イントロダクション"
---

# 自己紹介

## 略歴

### 学歴

-   学士（経営学），神戸大学2011年
-   修士（経営学），神戸大学2013年
-   博士（経営学），神戸大学2016年

### 職歴

-   松山大学経営学部講師→准教授 (2015-2022)
    -   WU Vienna, Research Visitor (2019)
    -   Georgetown University Visiting Scholar (2019-2020)
-   神戸大学大学院経営学研究科准教授 (2022-)

------------------------------------------------------------------------

### 専門

-   管理会計，特に業績評価システム

    -   従業員を評価し，報酬を与えることでやる気になってもらう

        -   どんな目標を設定すれば良いか？

        -   目標は途中で変えるべきか？

        -   上司の主観的評価の落とし穴は？

        -   創造的（クリエイティブ）なタスクはどう評価する？

-   企業のデータや実験により得たデータ，公表財務データなどを統計的に分析することで，これらの問題を研究しています。

# 社会調査？

## エビデンス・ベースト (evidence-based)という考え方

-   元々は医療分野の根拠に基づく医療（Evidence-BasedMedicine: EBM）
-   症例や臨床経験だけでなく，実験等で得られた証拠など，科学的根拠を活用した医療行為を行おう，という考え方
-   この考え方は，公共政策の分野（Evidence-Based Policy Making）や経営分野（Evidence-Based Management）に応用されつつある。
-   この考えの中では，エビデンスには複数のレベルがあるとされる。

### 参考: エビデンスレベル

-   これは，根拠に基づく医療（Evidence Based Medicine: EBM）という考え方の中の言葉
-   各研究方法から得られる証拠（エビデンス）をその信頼度で分類している
-   根拠に基づく政策立案（EBPM）や，根拠に基づく経営（EBMgt） @rousseau2006 として，経営学を含む他分野でも紹介されつつある

| Level | 内容                                                                                                                                                                                                                                                                                         |
|:----------------:|:-----------------------------------------------------|
|  1a   | [ランダム化比較試験](https://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%B3%E3%83%80%E3%83%A0%E5%8C%96%E6%AF%94%E8%BC%83%E8%A9%A6%E9%A8%93 "ランダム化比較試験")の[メタアナリシス](https://ja.wikipedia.org/wiki/%E3%83%A1%E3%82%BF%E3%82%A2%E3%83%8A%E3%83%AA%E3%82%B7%E3%82%B9 "メタアナリシス") |
|  1b   | 少なくとも一つの[ランダム化比較試験](https://ja.wikipedia.org/wiki/%E3%83%A9%E3%83%B3%E3%83%80%E3%83%A0%E5%8C%96%E6%AF%94%E8%BC%83%E8%A9%A6%E9%A8%93 "ランダム化比較試験") (RCT)                                                                                                             |
|  2a   | ランダム割付を伴わない同時コントロールを伴う[コホート研究](https://ja.wikipedia.org/wiki/%E3%82%B3%E3%83%9B%E3%83%BC%E3%83%88%E7%A0%94%E7%A9%B6 "コホート研究")（前向き研究、prospective study, concurrent cohort study）                                                                    |
|  2b   | ランダム割付を伴わない過去のコントロールを伴うコホート研究 (historical cohort study, retrospective cohort study)                                                                                                                                                                             |
|   3   | [症例対照研究](https://ja.wikipedia.org/wiki/%E7%97%87%E4%BE%8B%E5%AF%BE%E7%85%A7%E7%A0%94%E7%A9%B6 "症例対照研究")（ケースコントロール、後ろ向き研究）                                                                                                                                      |
|   4   | 処置前後の比較の前後比較、対照群を伴わない研究                                                                                                                                                                                                                                               |
|   5   | 症例報告、ケースシリーズ                                                                                                                                                                                                                                                                     |
|   6   | 専門家個人の意見（専門家委員会報告を含む）                                                                                                                                                                                                                                                   |

: エビデンスレベル一覧（[Wikipedia](https://ja.wikipedia.org/wiki/%E6%A0%B9%E6%8B%A0%E3%81%AB%E5%9F%BA%E3%81%A5%E3%81%8F%E5%8C%BB%E7%99%82)から）

### エビデンスの提供元としての社会調査

-   社会調査によって得られたデータの分析結果は，国家・地方公共団体の政策や企業の経営判断に役立てられる。
-   しかし，調査の仕方がまずかったり，分析の仕方がまずいと誤った結果をエビデンスとして提供してしまう可能性も
    -   関係のないものを関係あると示す
    -   関係のあるものを関係ないと示す
    -   正の関係のものを負の関係として示す

# 社会調査の流れ

-   社会調査は以下のような流れに従ってなされる

1.  リサーチ・クエスチョンの設定（問い）
2.  リサーチ・デザインの策定
3.  データ収集
4.  データ分析
5.  論文や報告書の作成（答え）

## リサーチクエスチョンの設定

-   調査の目的は，何かしらの新しい知識や情報を得ることにある
-   社会調査は調査なので，何かしら調査するべき課題・疑問がある
    -   まだわかっていないことの中で社会的もしくは理論的に重要なもの

## リサーチ・デザインの設定

-   問が定まっても，闇雲にアンケートを行えば良いわけではない。
    -   問いに関連してすでにわかっていること
    -   問いの答えとその理由に関する仮説を立てる
    -   データをどのように取るのかを検討する

## データ収集・分析

-   リサーチデザインに従って収集したデータを適切に分析して，仮説を検証する
-   仮説の検証結果を根拠に当初の問いの答えを決める

# この授業でやること

## 定量的データの分析

-   社会調査の一連の流れには，たくさんの論点があり全てを15回で扱うことはできません。
-   社会調査士プログラムの1授業として，この授業では定量的なデータの分析部分を中心に扱います。
    -   データの種類
    -   データのまとめ方
    -   母集団と標本
    -   推定と検定
    -   回帰分析
    -   分散分析
-   これは，得られたデータからなるべく間違いのない結果を提示するための方法に関する部分です

## プログラミング言語Rを使った分析
